### ISSUE TITLE
out node with zigbee2mqtt groups

### ISSUE THREAD

**Issue by 0uro** [Dirnei/node-red-contrib-zigbee2mqtt-devices#129]
Hi,

It seems that the out node has problems handling zigbee2mqtt groups.
It spits the following error : 
`TypeError: label.split is not a function`

That doesn't prevent the node to do its work though

**Comment by Andreas-Huber** [comment]
Hi 0uro,

Thank you for raising the issue, but I'm pretty sure you are in the wrong GitHub repo since this project does not have an `out` node. I think the project you are looking for is: https://github.com/andreypopov/node-red-contrib-zigbee2mqtt
The names are quite similar, so this confusion occurs from time to time. Therefore I'm closing this issue for now - feel free to comment if I'm wrong :-)

**Comment by 0uro** [comment]
You're right, I'm sorry
