### ISSUE TITLE
Generic-lamp node creating mqtt flood

### ISSUE THREAD

**Issue by alexinthis** [Dirnei/node-red-contrib-zigbee2mqtt-devices#45]
I am not sure what logs I can submit for this one. It also might be usual behavior, however, it's causing me issues.

I can force the issue when I hit deploy in node-red. By using MQTT.fx I subscribe to the node's messages and it floods out about 100 messages, they are all the same "{"linkquality":45,"state":"ON"}". 
The thing is I have about 10 nodes for all my lights and they all send ~100 messages. This then queues any new messages I send. So if I hit deploy then press my hue dimmer button it can take up to 15 seconds to send the command. It always works, you just have to wait. 

Throughout the day this seems to occur, a storm of messages that will delay a command I am trying to send. I end up pressing it a few times then all at once they come in once the message flood has finished. 

Versions:
node-red-contrib-zigbee2mqtt-devices: 0.15.2
node-red: 1.2.3
mosquitto: 1.6.10

**Comment by Dirnei** [comment]
Not sure who is flooding messages. Maybe I know what you mean, when you provide me a example message from your flood.

**Comment by Dirnei** [comment]
I took quite a while but now I may found the problem. For every deployment one additional state refresh request was sent. This was due to a bug I found yesterday. I didn't encountered the problem because I don't change much on my existing flow and haven't added more devices. 

Long story short: Bug is fixed and I also added a config to complete disable the refresh on the bridge to further reduce the messages.
