### ISSUE TITLE
climate-sensor is not updated to new device-selection

### ISSUE THREAD

**Issue by Dirnei** [Dirnei/node-red-contrib-zigbee2mqtt-devices#74]
Add new device-selection to the climate-sensor node.

**Comment by EnesE** [comment]
Is the issue for the bug that other devices are also displayed on the climate sensors?

If so than the issue is at all 3 sensors (contact, climate and occupancy).
If not than tell me and I open a new issue topic.

![image](https://user-images.githubusercontent.com/8766722/104955203-1ffef300-59ca-11eb-8eae-91d8c613f7c5.png)
![image](https://user-images.githubusercontent.com/8766722/104955220-28efc480-59ca-11eb-981b-80d10f0e9096.png)

**Comment by Dirnei** [comment]
It's not a bug. The filter is for EndDevices so all devices with a battery in it. But I think with z2m 1.17.0 I'm able to filter it more specifically

**Comment by Dirnei** [comment]
@EnesE I decided to create an extra issue. See #77

**Comment by EnesE** [comment]
> @EnesE I decided to create an extra issue. See #77

Alright. Thank you.
